var teamDict = {
    "xGjoEdLRwF": "Blue",
    "TBqHqnFOBI": "Blue",
    "xnJxPwlplf": "Blue",
    "ifCyYDgFOI": "Blue",
    "sMGzSAWPxn": "Blue",
    "YgbcHguOVq": "Blue",
    "zKUnFQZJkw": "Blue",
    "TbepKDDDRG": "Blue",
    "LprRNcAwIn": "Blue",
    "DuWwTTESaK": "Blue",
    "vuRXMLJOic": "Red",
    "RfjsQUyoMo": "Red",
    "josziMevFa": "Red",
    "BVzugztKEl": "Red",
    "LgInhercli": "Red",
    "hPNTpgkXZq": "Red",
    "FlePTnReXo": "Red",
    "VtceMRmmlX": "Red",
    "ExgNWQXyLc": "Red",
    "RUyimOyPDz": "Red"
};

var clueDict = {
    "Location 1": [L1clue1, L1clue2, L1clue3],
    "Location 2": [L2clue1, L2clue2, L2clue3],
    "Location 3": [L3clue1, L3clue2, L3clue3],
    "Location 4": [L4clue1, L4clue2, L4clue3],
    "Location 5": [L5clue1, L5clue2, L5clue3],
    "Location 6": [L6clue1, L6clue2, L6clue3],
    "Location 7": [L7clue1, L7clue2, L7clue3],
    "Location 8": [L8clue1, L8clue2, L8clue3],
    "Location 9": [L9clue1, L9clue2, L9clue3],
    "Location 10": [L10clue1, L10clue2, L10clue3],
};